services:
  postgres:
    image: postgres:16-alpine
    container_name: library
    restart: always
    environment:
      POSTGRES_USER: brugernavn
      POSTGRES_PASSWORD: adgangskode
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: